# Generated by Django 4.2.13 on 2024-07-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department_text', models.CharField(max_length=100)),
                ('complain_text', models.TextField()),
                ('complain_file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
