# Generated by Django 4.2.13 on 2024-07-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('surname', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('id_number', models.CharField(max_length=10)),
                ('institution_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('documents', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='email_text',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
