# Generated by Django 4.2.13 on 2024-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_applyattachment_alter_report_email_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='department_text',
            field=models.CharField(max_length=15),
        ),
    ]
