# Generated by Django 4.2.13 on 2024-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_report_department_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyattachment',
            name='documents',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='department_text',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
