# Generated by Django 4.2.13 on 2024-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_applyattachment_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='department_text',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
