# Generated by Django 4.2.13 on 2024-07-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_applyattachment_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyattachment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='institution_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
