# Generated by Django 4.2.13 on 2024-07-16 19:42

from django.db import migrations, models
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_applyattachment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date attended')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('id_num', models.CharField(blank=True, max_length=15, null=True)),
                ('time_in', models.TimeField(default=myapp.models.current_time, verbose_name='time in')),
                ('time_out', models.TimeField(default=myapp.models.current_time, verbose_name='time out')),
            ],
        ),
    ]
