# Generated by Django 4.2.13 on 2024-07-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='complain_text',
            field=models.TextField(null=True),
        ),
    ]
