# Generated by Django 4.2.13 on 2024-07-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_attendance_date_alter_attendance_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='complain_file',
            field=models.FileField(null=True, upload_to='complaints/', verbose_name='Complaint File'),
        ),
        migrations.AlterField(
            model_name='report',
            name='complain_text',
            field=models.TextField(default='complaints'),
        ),
        migrations.AlterField(
            model_name='report',
            name='department_text',
            field=models.CharField(default='department', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.CharField(default='phone', max_length=15),
        ),
    ]
