# Generated by Django 4.2.13 on 2024-07-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_report_email_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='email_text',
            field=models.EmailField(default='email', max_length=254),
        ),
    ]
