# Generated by Django 4.2.13 on 2024-07-18 22:56

from django.db import migrations, models
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_report_complain_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyattachment',
            name='email',
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='documents',
            field=models.FileField(default='documents', upload_to='', verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='first_name',
            field=models.CharField(default='first_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='id_number',
            field=models.CharField(default='id_number', max_length=10),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='institution_name',
            field=models.CharField(default='institution_name', max_length=254),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='phone_number',
            field=models.CharField(default='phone_number', max_length=15),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='second_name',
            field=models.CharField(default='second_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='applyattachment',
            name='surname',
            field=models.CharField(default='surname', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date attended'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(default='full_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id_num',
            field=models.CharField(default='id_num', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(default=myapp.models.current_time, verbose_name='time in'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(default=myapp.models.current_time, verbose_name='time out'),
        ),
        migrations.AlterField(
            model_name='report',
            name='complain_file',
            field=models.FileField(blank=True, default='complaints', null=True, upload_to='', verbose_name='Complaint File'),
        ),
    ]
